### ISSUE TITLE
I posted an example of fluxify.

### ISSUE THREAD

**Issue by uptimestar** [arqex/fluxify#10]
http://github.com/wgehner/flux 

As short as I could make it.

**Comment by arqex** [comment]
Hey @uptimestar!

There is been a while since anybody post in the fluxify repository.

I hope you liked the concept and you could learn about flux reading its code but I don't recommend you to use it since it's not maintained anymore.

Cheers

**Comment by cekvenich** [comment]
I’ll take over if u want. I’ll port it to ts. Let me know. It is very nice.

**Comment by arqex** [comment]
Hey @cekvenich 

That sounds great! I'd be glad if you want to maintain fluxify. Just send a nice PR, with something you would change in the code (maybe the port to ts would be too much for this "test PR" ) and I give you the permissions to be the maintainer of the project.

Cheers

**Comment by uptimestar** [comment]
great, will do. of course I to have to finish this other project first, but your project is very nice!
